name = "KiwiConstraintSolver"
uuid = "063317df-b1e6-4e84-b689-d7ba7b3726e4"
authors = ["Dheepak Krishnamurthy"]
version = "1.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"

[compat]
DataStructures = "0.18"
InlineTest = "0.2"
ReTest = "0.3"
julia = "1.8"

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"

[targets]
test = ["ReTest"]
